name: "Context Examples"

on: [push]

jobs:
  my_context:
      runs-on: ubuntu-latest
      steps:
        - name: "My Step"
          env:
            MY_ACTION: ${{ github.action }}
            MY_ACTOR: ${{ github.actor }}
          run: |
            echo "Actor : ${MY_ACTOR}"
            echo "Action: ${MY_ACTION}"

                